# Generated by Django 3.1 on 2020-08-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200829_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_add',
            new_name='dateofadd',
        ),
    ]
