# Generated by Django 3.1 on 2020-08-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePercentage',
            fields=[
                ('percentage', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='percentage for the service')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of the status')),
            ],
        ),
    ]
