# Generated by Django 3.1 on 2020-09-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200906_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='meals',
            new_name='meal',
        ),
    ]
