# Generated by Django 3.1 on 2020-08-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200829_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepercentage',
            name='id',
        ),
        migrations.AlterField(
            model_name='servicepercentage',
            name='percentage',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='percentage for the service'),
        ),
    ]
