# Generated by Django 3.1 on 2020-09-06 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200906_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.onemealtoorder'),
        ),
    ]
