# Generated by Django 3.1 on 2020-09-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200906_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='meal',
        ),
    ]
